apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler   # ðŸ‘ˆ Type of object
metadata:
  name: nginx-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment      # ðŸ‘ˆ Which Deployment to scale
  minReplicas: 1                # ðŸ‘ˆ Minimum pods
  maxReplicas: 5                # ðŸ‘ˆ Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # ðŸ‘ˆ If CPU > 50%, add more pods
